TARGET:HALinkedListApi.o LinkedListApi.o
HALinkedListApi.o:HALinkedListApi.c
	gcc -g -c -I . -I ./../../ HALinkedListApi.c -o HALinkedListApi.o
LinkedListApi.o:LinkedListApi.c
	gcc -g -c -I . -I ./../../ LinkedListApi.c -o LinkedListApi.o
clean:
	rm HALinkedListApi.o
	rm LinkedListApi.o
